//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayGood2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public int Role { get; set; }
        public Nullable<int> Got { get; set; }
        public Nullable<int> Give { get; set; }
        public string Pic { get; set; }
    }
}
