//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayGood2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int UpdateId { get; set; }
        public string Name { get; set; }
        public System.DateTime UpDate { get; set; }
        public string Desc { get; set; }
        public string ToWho { get; set; }
    }
}
